### ISSUE TITLE
✖ Generating FrameProcessor fails

### ISSUE THREAD

**Issue by jeremyspritelyco** [mateusz1913/vision-camera-plugin-builder#21]
### Environment

node version: 16.16.0

### Is used with npx or as a local dependency?

- [X] npx
- [ ] local dependency

### Affected commands

- [ ] android
- [X] ios

### Current behavior

```
✔ What is the name of the plugin? … EyeFrameProcessor
✔ What is the name of plugin's exported method? … labelImageWithYolo
✔ What language do you want to use to develop plugin? › Swift
✖ Generating EyeFrameProcessor

/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Users/jeremynguyen/.npm/_npx/34cdf8892b0db400/node_modules/vision-camera-plugin-builder/generateIOS.rb:1:in `<main>'

Command failed: ruby /Users/jeremynguyen/.npm/_npx/34cdf8892b0db400/node_modules/vision-camera-plugin-builder/generateIOS.rb /Volumes/T7Touch/work/golden_owl/react-native-test-2-main/ios/reactNativeTest2.xcodeproj EyeFrameProcessor labelImageWithYolo Swift
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /Users/jeremynguyen/.npm/_npx/34cdf8892b0db400/node_modules/vision-camera-plugin-builder/generateIOS.rb:1:in `<main>'
```

### Expected behavior

I need things successfully generated.

### Reproduction repository link

it fails to generate, how I can have a repo for you?

**Comment by mateusz1913** [comment]
@jeremyspritelyco did you install `xcodeproj` before as it is stated in README?
The error message clearly suggests that your Ruby cannot find `xcodeproj` gem and it is required for generating files & appending them to xcode project files

**Comment by mateusz1913** [comment]
Closing due to inactivity
